### ISSUE TITLE
The Peaq Node is not starting

### ISSUE THREAD

**Issue by vvsima** [peaqnetwork/peaq-network-node#23]
I used the Node Installation Guide
`https://docs.peaq.io/node-operators/run-an-agung-node-peaq-testnet/peaq-node-installation-guide`

I downloaded the file
`https://github.com/peaqnetwork/peaq-network-node/releases/download/agung-apr-7-2022/peaq-node-agung-apr-7-2022.tar.gz`
unpacked its contents and installed and mark it as executable.

I got an error when trying to launch:
`Error: Input("Error opening spec file ``: No such file or directory (os error 2)")`

![screenshot 2022-04-26 113156](https://user-images.githubusercontent.com/84487308/165224744-c11d7ce1-7aa5-45f3-89d6-93db649b0532.jpg)

**Environment**
- Operating system: Ubuntu 20.04.4 LTS
- Total memory: 8Gb
- Processor: Intel Xeon, 4 Core

**Comment by kamrangul2404** [comment]
Kindly use the command below to run the node.
./peaq-node --chain agung

**Comment by vvsima** [comment]
Ok. Syncing has started.

In the node installation guide, you should also correct the name of the archive file. On github now the file is named 
`peaq-node-agung-apr-7-2022.tar.gz`

![image](https://user-images.githubusercontent.com/84487308/165289761-8e6a77af-38d2-4da9-a8cf-ea2f4ca11419.png)

**Comment by vvsima** [comment]
In the startup script _start_node.sh_ it should be like in the guide
`--chain local`
or should I change to
`--chain agung`
??

**Comment by Hyr6767** [comment]
hi

**Comment by sfffaaa** [comment]
Close this issue because currently we are the parachain and the README has updated
